set t_Co=256
set nocompatible
set encoding=utf-8
set shell=/bin/zsh

" ------------------------------------------------------------------------------
" Plugin Manager
" ------------------------------------------------------------------------------
execute pathogen#infect()
syntax on
filetype plugin indent on

set number
set linebreak
set showbreak=+++
set showmatch
set visualbell

set hlsearch
set smartcase
set ignorecase
set incsearch

set autoindent
set cindent
set expandtab
set shiftwidth=4
set smartindent
set smarttab
set softtabstop=4
set nowrap
set ruler
set undolevels=1000
set backspace=indent,eol,start

" ------------------------------------------------------------------------------
" Airline
" ------------------------------------------------------------------------------
set laststatus=2
set encoding=utf-8
let g:airline_powerline_fonts = 1
" Enable the list of buffers
" let g:airline#extensions#tabline#enabled = 1
" let g:airline#extensions#tabline#fnamemod = ':t'

" ------------------------------------------------------------------------------
" Gruvbox theme
" ------------------------------------------------------------------------------
set background=dark    " Setting dark mode
colorscheme gruvbox

" ------------------------------------------------------------------------------
" Disable wrap
" ------------------------------------------------------------------------------
set textwidth=0
set wrapmargin=0

" ------------------------------------------------------------------------------
" remap keys
" ------------------------------------------------------------------------------
inoremap jk <ESC>
let mapleader = "\<Space>"

" ------------------------------------------------------------------------------
" GVIM
" ------------------------------------------------------------------------------
set guifont=Source\ Code\ Pro\ Medium\ 10
set guioptions-=m  "remove menu bar
set guioptions-=T  "remove toolbar
set guioptions-=r  "remove toolbar
set guioptions-=L  "remove left-hand scroll bar
set guiheadroom=0

" ------------------------------------------------------------------------------
" Autoreload vimrc
" ------------------------------------------------------------------------------
augroup myvimrc
    au!
    au BufWritePost ~/.vimrc so $MYVIMRC
augroup END

" ------------------------------------------------------------------------------
" CtrlP
" ------------------------------------------------------------------------------
set runtimepath^=~/.vim/bundle/ctrlp.vim

" Setup some default ignores
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\v[\/](\.(git|hg|svn)|\_site)$',
  \ 'file': '\v\.(exe|so|dll|class|png|jpg|jpeg|pdf|svg)$',
  \}

" Use the nearest .git directory as the cwd
" This makes a lot of sense if you are working on a project that is in version
" control. It also supports works with .svn, .hg, .bzr.
let g:ctrlp_working_path_mode = 'r'

" Use a leader instead of the actual named binding
nmap <leader>p :CtrlP<cr>

" Easy bindings for its various modes
nmap <leader>bb :CtrlPBuffer<cr>
nmap <leader>bm :CtrlPMixed<cr>
nmap <leader>bs :CtrlPMRU<cr>

" ------------------------------------------------------------------------------
" buffergator
" ------------------------------------------------------------------------------
" Use the right side of the screen
let g:buffergator_viewport_split_policy = 'R'

" I want my own keymappings...
let g:buffergator_suppress_keymaps = 1

" Looper buffers
"let g:buffergator_mru_cycle_loop = 1

" Go to the previous buffer open
nmap <leader>jj :BuffergatorMruCyclePrev<cr>

" Go to the next buffer open
nmap <leader>kk :BuffergatorMruCycleNext<cr>

" View the entire list of buffers open
nmap <leader>bl :BuffergatorOpen<cr>

" Shared bindings from Solution #1 from earlier
nmap <leader>T :enew<cr>
nmap <leader>bq :bp <BAR> bd #<cr>

