# MIPS toolchain
#  export PATH=/opt/mgc/embedded/codebench/bin:$PATH
# export MANPATH=/opt/mgc/embedded/codebench/share/doc/mips-mips-sde-elf/man:$MANPATH

# RISCV toolchain
export PATH=/opt/riscv/bin:$PATH
export LD_LIBRARY_PATH=/opt/riscv/lib/:$LD_LIBRARY_PATH
export MANPATH=/opt/riscv/share/man:$MANPATH

# Color
export TERM=xterm-256color

# CUDA
export CUDA_HOME=/opt/cuda
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:$LD_LIBRARY_PATH

PATH=${CUDA_HOME}/bin:${PATH}
export PATH

# default editor
export EDITOR=vim

# ROS
# Do this at the end
source /opt/ros/jade/setup.zsh
alias catkin_make='catkin_make -DPYTHON_EXECUTABLE=/usr/bin/python2 -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so'
alias catkin_make_isolated='catkin_make_isolated -DPYTHON_EXECUTABLE=/usr/bin/python2 -DPYTHON_INCLUDE_DIR=/usr/include/python2.7 -DPYTHON_LIBRARY=/usr/lib/libpython2.7.so'

# Xilinx tools
export XILINX=/opt/Xilinx/14.7/ISE_DS
export PATH=${PATH}:${XILINX}/ISE/bin/lin64:${XILINX}/EDK/bin/lin64/:${XILINX}/PlanAhead/bin
export _JAVA_AWT_WM_NONREPARENTING=1

# Haskell
# export PATH=~/.cabal/bin/:$PATH
